package main

type AutoGenerated struct {
	Leagues []Leagues `json:"leagues"`
	Season  Season    `json:"season"`
	Day     Day       `json:"day"`
	Events  []Events  `json:"events"`
}
type Type struct {
	ID           string `json:"id"`
	Type         int    `json:"type"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
}
type Season struct {
	Year      int    `json:"year"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	Type      Type   `json:"type"`
}
type Leagues struct {
	ID                  string   `json:"id"`
	UID                 string   `json:"uid"`
	Name                string   `json:"name"`
	Abbreviation        string   `json:"abbreviation"`
	Slug                string   `json:"slug"`
	Season              Season   `json:"season"`
	CalendarType        string   `json:"calendarType"`
	CalendarIsWhitelist bool     `json:"calendarIsWhitelist"`
	CalendarStartDate   string   `json:"calendarStartDate"`
	CalendarEndDate     string   `json:"calendarEndDate"`
	Calendar            []string `json:"calendar"`
}
type Season struct {
	Type int `json:"type"`
	Year int `json:"year"`
}
type Day struct {
	Date string `json:"date"`
}
type Type struct {
	ID string `json:"id"`
}
type Address struct {
	City  string `json:"city"`
	State string `json:"state"`
}
type Venue struct {
	ID       string  `json:"id"`
	FullName string  `json:"fullName"`
	Address  Address `json:"address"`
	Capacity int     `json:"capacity"`
	Indoor   bool    `json:"indoor"`
}
type Venue struct {
	ID string `json:"id"`
}
type Links struct {
	Rel        []string `json:"rel"`
	Href       string   `json:"href"`
	Text       string   `json:"text"`
	IsExternal bool     `json:"isExternal"`
	IsPremium  bool     `json:"isPremium"`
}
type Team struct {
	ID               string  `json:"id"`
	UID              string  `json:"uid"`
	Location         string  `json:"location"`
	Name             string  `json:"name"`
	Abbreviation     string  `json:"abbreviation"`
	DisplayName      string  `json:"displayName"`
	ShortDisplayName string  `json:"shortDisplayName"`
	Color            string  `json:"color"`
	AlternateColor   string  `json:"alternateColor"`
	IsActive         bool    `json:"isActive"`
	Venue            Venue   `json:"venue"`
	Links            []Links `json:"links"`
	Logo             string  `json:"logo"`
}
type Linescores struct {
	Value float64 `json:"value"`
}
type Statistics struct {
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	DisplayValue string `json:"displayValue"`
}
type Links struct {
	Rel  []string `json:"rel"`
	Href string   `json:"href"`
}
type Position struct {
	Abbreviation string `json:"abbreviation"`
}
type Team struct {
	ID string `json:"id"`
}
type Athlete struct {
	ID          string   `json:"id"`
	FullName    string   `json:"fullName"`
	DisplayName string   `json:"displayName"`
	ShortName   string   `json:"shortName"`
	Links       []Links  `json:"links"`
	Jersey      string   `json:"jersey"`
	Headshot    string   `json:"headshot"`
	Position    Position `json:"position"`
	Team        Team     `json:"team"`
	Active      bool     `json:"active"`
}
type Leaders struct {
	DisplayValue string  `json:"displayValue"`
	Value        float64 `json:"value"`
	Athlete      Athlete `json:"athlete"`
	Team         Team    `json:"team"`
}
type Leaders struct {
	Name             string    `json:"name"`
	DisplayName      string    `json:"displayName"`
	ShortDisplayName string    `json:"shortDisplayName"`
	Abbreviation     string    `json:"abbreviation"`
	Leaders          []Leaders `json:"leaders"`
}
type Records struct {
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation,omitempty"`
	Type         string `json:"type"`
	Summary      string `json:"summary"`
}
type Competitors struct {
	ID         string       `json:"id"`
	UID        string       `json:"uid"`
	Type       string       `json:"type"`
	Order      int          `json:"order"`
	HomeAway   string       `json:"homeAway"`
	Team       Team         `json:"team"`
	Score      string       `json:"score"`
	Linescores []Linescores `json:"linescores"`
	Statistics []Statistics `json:"statistics"`
	Leaders    []Leaders    `json:"leaders"`
	Records    []Records    `json:"records"`
}
type Probability struct {
	TiePercentage     float64 `json:"tiePercentage"`
	HomeWinPercentage float64 `json:"homeWinPercentage"`
	AwayWinPercentage float64 `json:"awayWinPercentage"`
}
type LastPlay struct {
	ID          string      `json:"id"`
	Type        Type        `json:"type"`
	Text        string      `json:"text"`
	ScoreValue  int         `json:"scoreValue"`
	Team        Team        `json:"team"`
	Probability Probability `json:"probability"`
}
type Situation struct {
	LastPlay LastPlay `json:"lastPlay"`
}
type Type struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	State       string `json:"state"`
	Completed   bool   `json:"completed"`
	Description string `json:"description"`
	Detail      string `json:"detail"`
	ShortDetail string `json:"shortDetail"`
}
type Status struct {
	Clock        float64 `json:"clock"`
	DisplayClock string  `json:"displayClock"`
	Period       int     `json:"period"`
	Type         Type    `json:"type"`
}
type Broadcasts struct {
	Market string   `json:"market"`
	Names  []string `json:"names"`
}
type Type struct {
	ID        string `json:"id"`
	ShortName string `json:"shortName"`
}
type Market struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}
type Media struct {
	ShortName string `json:"shortName"`
}
type GeoBroadcasts struct {
	Type   Type   `json:"type"`
	Market Market `json:"market"`
	Media  Media  `json:"media"`
	Lang   string `json:"lang"`
	Region string `json:"region"`
}
type Competitions struct {
	ID                    string          `json:"id"`
	UID                   string          `json:"uid"`
	Date                  string          `json:"date"`
	Attendance            int             `json:"attendance"`
	Type                  Type            `json:"type"`
	TimeValid             bool            `json:"timeValid"`
	NeutralSite           bool            `json:"neutralSite"`
	ConferenceCompetition bool            `json:"conferenceCompetition"`
	Recent                bool            `json:"recent"`
	Venue                 Venue           `json:"venue"`
	Competitors           []Competitors   `json:"competitors"`
	Notes                 []interface{}   `json:"notes"`
	Situation             Situation       `json:"situation"`
	Status                Status          `json:"status"`
	Broadcasts            []Broadcasts    `json:"broadcasts"`
	StartDate             string          `json:"startDate"`
	GeoBroadcasts         []GeoBroadcasts `json:"geoBroadcasts"`
}
type Links struct {
	Language   string   `json:"language"`
	Rel        []string `json:"rel"`
	Href       string   `json:"href"`
	Text       string   `json:"text"`
	ShortText  string   `json:"shortText"`
	IsExternal bool     `json:"isExternal"`
	IsPremium  bool     `json:"isPremium"`
}
type Events struct {
	ID           string         `json:"id"`
	UID          string         `json:"uid"`
	Date         string         `json:"date"`
	Name         string         `json:"name"`
	ShortName    string         `json:"shortName"`
	Season       Season         `json:"season"`
	Competitions []Competitions `json:"competitions"`
	Links        []Links        `json:"links"`
	Status       Status         `json:"status"`
}